name: Publish App to Google Play Internal Testing
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-b[0-9]+'

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Extract secrets
        run: |
          mkdir .keys
          echo -n "${{ secrets.SIGNING_KEY }}" | base64 --decode > .keys/app_sign.jks
          echo -n "${{ secrets.IRFC_RELEASE_CI_API_JSON }}" | base64 --decode > .keys/service-account.json

      - name: Create APK & Bundle
        run: ./gradlew assembleRelease bundleRelease -PkeyPassword=${{ secrets.KEY_PASSWORD }} -PstorePassword=${{ secrets.KEYSTORE_PASSWORD }} -PkeyAlias=${{ secrets.KEYSTORE_ALIAS }}

      - name: Upload APK & Bundle
        uses: actions/upload-artifact@v3
        with:
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab

      - name: Upload to PlayStore internal Testing
        run: ./gradlew publishReleaseApps -PkeyPassword=${{ secrets.KEY_PASSWORD }} -PstorePassword=${{ secrets.KEYSTORE_PASSWORD }} -PkeyAlias=${{ secrets.KEYSTORE_ALIAS }}

      # TODO send notification (Teams/Slack/...)?